[workspace]
members = [
    "jeriya",
    "jeriya_backend_ash",
    "jeriya_shared",
    "jeriya_test",
    "jeriya_macros",
    "jeriya_content",
    "jeriya_viewer",
    "jeriya_backend",
    "jeriya_tool",
]
resolver = "2"
