[package]
name = "jeriya_shared"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.24"
log = "0.4.17"
parking_lot = "0.12.1"
winit = "0.28.3"
nalgebra = "0.32.2"
nalgebra-glm = "0.18.0"
bitflags = "2.1.0"