#version 450

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

layout (constant_id = 0) const uint MAX_CAMERAS = 8;
layout (constant_id = 1) const uint MAX_INANIMATE_MESH_INSTANCES = 1024;
layout (constant_id = 2) const uint MAX_INANIMATE_MESHES = 1024;

struct Camera {
    mat4 projection_matrix;
    mat4 view_matrix;
    mat4 matrix;
};

struct InanimateMeshInstance {
    uint64_t inanimate_mesh_id;
    mat4 transform;
};

struct VkDrawIndirectCommand {
    uint vertex_count;
    uint instance_count;
    uint first_vertex;
    uint first_instance;
};

struct InanimateMesh {
    uint64_t vertices_start_offset;
    uint64_t vertices_len;
    uint64_t indices_start_offset;
    uint64_t indices_len;
};

layout (set = 0, binding = 0) uniform PerFrameData { 
    uint active_camera;
    uint inanimate_mesh_instance_count;
} per_frame_data;

layout (set = 0, binding = 1) buffer Cameras { 
    Camera cameras[MAX_CAMERAS];
} cameras;

layout (set = 0, binding = 2) buffer InanimateMeshInstances { 
    InanimateMeshInstance inanimate_mesh_instances[MAX_INANIMATE_MESH_INSTANCES];
} inanimate_mesh_instances;

layout (set = 0, binding = 3) buffer IndirectDrawInanimateMeshInstances { 
    VkDrawIndirectCommand indirect_draw_inanimate_mesh_instances[MAX_INANIMATE_MESH_INSTANCES];
};

layout (set = 0, binding = 4) buffer InanimateMeshes { 
    InanimateMesh inanimate_meshes[MAX_INANIMATE_MESHES];
};

layout (set = 0, binding = 5) buffer StaticVertexBuffer {
    vec4 vertices[];
};

layout (set = 0, binding = 6) buffer StaticIndexBuffer {
    vec4 indices[];
};





layout (local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint index = gl_GlobalInvocationID.x;
    if (index >= per_frame_data.inanimate_mesh_instance_count) {
        return;
    }

    uint64_t mesh_id = inanimate_mesh_instances.inanimate_mesh_instances[index].inanimate_mesh_id;

    InanimateMesh inanimate_mesh = inanimate_meshes[uint(mesh_id)];

    VkDrawIndirectCommand draw_indirect_command;
    draw_indirect_command.vertex_count = uint(inanimate_mesh.vertices_len);
    draw_indirect_command.instance_count = 1;
    draw_indirect_command.first_vertex = 0;
    draw_indirect_command.first_instance = 0;

    indirect_draw_inanimate_mesh_instances[index] = draw_indirect_command;
}