[package]
name = "jeriya_backend"
version = "0.3.0"
edition = "2021"

[features]
test-utils = [] # Enables types and functions for testing

[dependencies]
jeriya_shared = { path = "../jeriya_shared" }
jeriya_content = { path = "../jeriya_content" }
jeriya_test = { path = "../jeriya_test" }
