[package]
name = "jeriya_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
jeriya_shared = { path = "../jeriya_shared" }
jeriya_content = { path = "../jeriya_content" }
clap = { version = "4.4.7", features = ["derive"] }
color-eyre = "0.6.2"
fern = "0.6.1"
