permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

name: clippy
jobs:
  clippy:
    runs-on: windows-latest
    name: clippy
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features