permissions:
  contents: read

on:
  push:
    branches: ["**"]
  pull_request:

name: doc
jobs:
  doc:
    runs-on: windows-latest
    name: doc
    steps:
      - uses: actions/checkout@v4

      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.1

      - name: cargo doc
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: --cfg docsrs
