name: examples

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  examples:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.6.2

      - name: Examples
        run: cargo build --examples
