name: examples

on:
  push:
    branches: ["**"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  examples:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3

      - name: Examples
        run: cargo build --examples
