permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

name: format
jobs:
  format:
    runs-on: windows-latest
    name: fmt
    steps:
      - uses: actions/checkout@v3
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: cargo fmt --check
        run: cargo fmt --check
