permissions:
  contents: read

on:
  push:
    branches: ["**"]
  pull_request:

name: format
jobs:
  format:
    runs-on: windows-latest
    name: fmt
    steps:
      - uses: actions/checkout@v4

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3

      - name: cargo fmt --check
        run: cargo fmt --check
